-- Inkbound audio (client): pooled SFX with variation + distance falloff, crossfading music, pencil scratch.
-- Ids live in SoundIds.lua (generated by tools/audio/upload.py). Missing ids fall back to built-in sounds.
local SoundService = game:GetService("SoundService")
local TweenService = game:GetService("TweenService")
local Players = game:GetService("Players")

local Ids = require(script.Parent:WaitForChild("SoundIds"))

local Audio = {}
Audio.sfxVolume = 1
Audio.musicVolume = 0.35

-- built-in fallbacks (ship with every Roblox client)
local B = {
	click = "rbxasset://sounds/button.wav",
	swoosh = "rbxasset://sounds/swoosh.wav",
	ping = "rbxasset://sounds/electronicpingshort.wav",
	snap = "rbxasset://sounds/snap.wav",
	splat = "rbxasset://sounds/splat.wav",
	boom = "rbxasset://sounds/collide.wav",
}
local FALLBACK = {
	ui_click = B.click, ui_open = B.swoosh, place = B.swoosh, reveal_tick = B.click, upgrade = B.ping, masterpiece = B.ping,
	sell = B.ping, hit1 = B.snap, hit2 = B.snap, hit3 = B.snap, death = B.splat, boss_death = B.boom, leak = B.splat,
	slash = B.swoosh, arrow = B.swoosh, magic = B.ping, boom = B.boom, punch = B.snap, el_fire = B.swoosh, el_frost = B.ping,
	el_storm = B.snap, el_nature = B.swoosh, el_void = B.swoosh, el_holy = B.ping, wave_start = B.ping, wave_clear = B.ping,
	boss_warn = B.boom, game_over = B.splat, combo = B.ping, countdown = B.click, go = B.ping, heal = B.ping, erase = B.swoosh,
	reveal_common = B.ping, reveal_uncommon = B.ping, reveal_rare = B.ping, reveal_epic = B.ping, reveal_legendary = B.ping,
	reveal_mythic = B.ping, reveal_godlike = B.ping,
}
-- per-sound mix levels (tuned against each other; SFX sit under the music's -15 dB RMS)
local LEVEL = {
	ui_click = 0.45, ui_open = 0.5, place = 0.8, reveal_tick = 0.35, hit1 = 0.35, hit2 = 0.35, hit3 = 0.35, death = 0.5,
	slash = 0.4, arrow = 0.35, magic = 0.3, punch = 0.4, el_fire = 0.35, el_frost = 0.35, el_storm = 0.35, el_nature = 0.35,
	el_void = 0.4, el_holy = 0.35, boom = 0.6, leak = 0.8, boss_warn = 0.7, draw_scratch = 0.0,
	void_place = 0.55, jump_pad = 0.6, wind = 0.3, level_up = 0.6, game_over = 0.6, masterpiece = 0.6, reveal_godlike = 0.8, countdown = 0.5, wave_start = 0.5,
}
-- minimum gap between repeats (stops 30 towers firing at once turning into noise)
local GAP = { hit1 = 0.05, hit2 = 0.05, hit3 = 0.05, death = 0.04, slash = 0.06, arrow = 0.05, magic = 0.07, punch = 0.05,
	jump_pad = 0.3, wind = 0.5, el_fire = 0.12, el_frost = 0.12, el_storm = 0.1, el_nature = 0.12, el_void = 0.15, el_holy = 0.2, boom = 0.08, reveal_tick = 0.02 }

local function idFor(name)
	local id = Ids[name]
	if type(id) == "table" then -- v10.2: several variants -> random one each time
		id = id[math.random(#id)]
	end
	if type(id) == "number" and id > 0 then
		return "rbxassetid://" .. id, true
	end
	if type(id) == "string" and id ~= "" and id ~= "0" then
		return id, true
	end
	return FALLBACK[name], false
end

local templates = {}
local group = Instance.new("SoundGroup")
group.Name = "InkSFX"
group.Parent = SoundService
local musicGroup = Instance.new("SoundGroup")
musicGroup.Name = "InkMusic"
musicGroup.Parent = SoundService

local function template(name)
	local key = name
	local id, real
	if type(Ids[name]) == "table" then
		id, real = idFor(name)
		key = name .. "#" .. tostring(id)
	end
	local t = templates[key]
	if t == nil then
		if not id then
			id, real = idFor(name)
		end
		if not id then
			templates[key] = false
			return false
		end
		t = Instance.new("Sound")
		t.Name = name
		t.SoundId = id
		t.Volume = LEVEL[name] or 0.6
		t.SoundGroup = group
		t:SetAttribute("Real", real)
		t.Parent = group
		templates[key] = t
	end
	return t
end

local last = {}
local live = 0
local MAX_LIVE = 24
-- play(name, {pitch=, vol=, pos=Vector3, vary=0.06})
function Audio.play(name, opts)
	opts = opts or {}
	local now = os.clock()
	if last[name] and now - last[name] < (GAP[name] or 0.03) then
		return
	end
	if live >= MAX_LIVE then
		return
	end
	local t = template(name)
	if not t then
		return
	end
	local vol = t.Volume * (opts.vol or 1) * Audio.sfxVolume
	if opts.pos then
		local cam = workspace.CurrentCamera
		local d = cam and (cam.CFrame.Position - opts.pos).Magnitude or 0
		vol *= math.clamp(1.15 - d / 180, 0, 1)
		if vol < 0.03 then
			return
		end
	end
	last[name] = now
	local s = t:Clone()
	local vary = opts.vary or 0.06
	s.PlaybackSpeed = (opts.pitch or 1) * (1 + (math.random() * 2 - 1) * vary)
	s.Volume = vol
	s.Parent = group
	live += 1
	s.Ended:Once(function()
		live -= 1
		s:Destroy()
	end)
	task.delay(6, function()
		if s.Parent then
			live -= 1
			s:Destroy()
		end
	end)
	s:Play()
	return s
end

-- v10.1 SOUND LAB: swap a slot's id live (admin audition) and preview any asset id
function Audio.override(name, id)
	Ids[name] = id
	for k, t in pairs(templates) do
		if k == name or string.sub(k, 1, #name + 1) == name .. "#" then
			if t then
				t:Destroy()
			end
			templates[k] = nil
		end
	end
end
function Audio.current(name)
	return Ids[name]
end
local previewSound
function Audio.preview(id, vol)
	if previewSound then
		previewSound:Destroy()
	end
	local s = Instance.new("Sound")
	s.SoundId = "rbxassetid://" .. tostring(id)
	s.Volume = vol or 0.6
	s.Parent = SoundService
	previewSound = s
	s:Play()
	task.delay(12, function()
		if s.Parent then
			s:Destroy()
		end
	end)
	return s
end
function Audio.stopPreview()
	if previewSound then
		previewSound:Destroy()
		previewSound = nil
	end
end

-- random hit variant
function Audio.hit(pos, big)
	Audio.play("hit" .. math.random(1, 3), { pos = pos, pitch = big and 0.85 or 1, vary = 0.1 })
end

---------------------------------------------------------------------------
-- music with crossfade
---------------------------------------------------------------------------
local current, currentName
function Audio.music(name, fadeTime)
	if name == currentName then
		return
	end
	currentName = name
	fadeTime = fadeTime or 1.5
	local old = current
	if old then
		TweenService:Create(old, TweenInfo.new(fadeTime), { Volume = 0 }):Play()
		task.delay(fadeTime + 0.1, function()
			old:Destroy()
		end)
	end
	current = nil
	if not name then
		return
	end
	local id, real = idFor(name)
	if not id or not real then
		return -- no fallback music (built-in sounds are SFX only)
	end
	local s = Instance.new("Sound")
	s.Name = name
	s.SoundId = id
	s.Looped = true
	s.Volume = 0
	s.SoundGroup = musicGroup
	s.Parent = musicGroup
	s:Play()
	TweenService:Create(s, TweenInfo.new(fadeTime), { Volume = Audio.musicVolume }):Play()
	current = s
end
function Audio.setMusicVolume(v)
	Audio.musicVolume = v
	if current then
		current.Volume = v
	end
end

---------------------------------------------------------------------------
-- pencil scratch (looping, volume + pitch follow stroke speed)
---------------------------------------------------------------------------
local scratch
function Audio.scratch(speed)
	-- speed: canvas units / second (0 = pen lifted)
	if not scratch then
		local id, real = idFor("draw_scratch")
		if not real then
			return -- the built-in fallback doesn't loop nicely; stay quiet until uploaded
		end
		scratch = Instance.new("Sound")
		scratch.SoundId = id
		scratch.Looped = true
		scratch.Volume = 0
		scratch.SoundGroup = group
		scratch.Parent = group
		scratch:Play()
	end
	local k = math.clamp(speed / 250, 0, 1)
	local target = k > 0.02 and (0.12 + 0.45 * k) * Audio.sfxVolume or 0
	-- smooth so it doesn't flutter frame to frame
	scratch.Volume += (target - scratch.Volume) * 0.35
	scratch.PlaybackSpeed = 0.85 + 0.45 * k
end

_ = Players
return Audio
